/** @format */

export const Types = {
	GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
	SET_LOADING: 'SET_LOADING',
	CHANGE_PAGE: 'CHANGE_PAGE',
	GET_PRODUCT_CATEGORIES: 'GET_PRODUCT_CATEGORIES',
	FILTER_TYPE: 'FILTER_TYPE',
	FILTER_BRAND: 'FILTER_BRAND',
	FILTER_RATING: 'FILTER_RATING',
	SEARCH_PRODUCT: 'SEARCH_PRODUCT',
	CLEAR_FILTER: 'CLEAR_FILTER',
	FIND_BY_PRICE: 'FIND_BY_PRICE',
	SORT_PRICE: 'SORT_PRICE',
};
